apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: learning-platform
type: Opaque
stringData:
  # PostgreSQL
  postgres-user: "course_user"
  postgres-password: "course_password"
  postgres-db: "course_db"

  # MinIO
  minio-root-user: "minioadmin"
  minio-root-password: "minioadmin"

  # Shared JWT
  jwt-secret-key: "change-me-shared-jwt-secret"

  # User-service email (optional)
  email-user: ""
  email-password: ""