apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: learning-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z course-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-redis
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
      - name: analytics-service
        image: kadhemsellami/elearning-analytics-service-image:v1.0  # My registry's custom built image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: ANALYTICS_BACKEND_ENV
          value: "dev"
        - name: ANALYTICS_BACKEND_PORT
          value: "8003"
        - name: ANALYTICS_BACKEND_POSTGRES_URL
          value: "postgresql://course_user:course_password@course-postgres:5432/course_db"
        - name: ANALYTICS_BACKEND_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret-key
        - name: ANALYTICS_BACKEND_JWT_ALGORITHM
          value: "HS256"
        - name: ANALYTICS_BACKEND_REDIS_HOST
          value: "redis"
        - name: ANALYTICS_BACKEND_REDIS_PORT
          value: "6379"
        - name: ANALYTICS_BACKEND_REDIS_TTL_SECONDS
          value: "60"
        - name: ANALYTICS_BACKEND_APP_NAME
          value: "Analytics Service"
        - name: ANALYTICS_BACKEND_LOG_LEVEL
          value: "DEBUG"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 25
          periodSeconds: 15
          timeoutSeconds: 7
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 25
          periodSeconds: 15
          timeoutSeconds: 7
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: learning-platform
spec:
  selector:
    app: analytics-service
  ports:
  - port: 8003
    targetPort: 8003
    name: http